### PR TITLE
updated to sinon 1.4.2 and added support for calledWithMatch/alwaysCalledWithMatch

### PR DESCRIPTION
**Pull request by theinterned**

### CODE REVIEW

**Comment by theinterned** [comment]
... I may get around to adding in the rest of the missing spy api as well ... but I'm scratching my own itch for now

**Comment by ream88** [comment]
Please please merge this!

**Comment by froots** [comment]
Thanks for this @theinterned and thanks for the reminder @haihappen! :blush:

**Comment by theinterned** [comment]
cheers!

**Pull request merged**
